### ISSUE TITLE
node-gyp configure build failed

### ISSUE THREAD

**Issue by kud** [askovpen/node-fidonet-mailer-binkp-crypt#1]
node: `0.12`

```
> fidonet-mailer-binkp-crypt@0.0.21 install /Users/kud/Projects/_playmedia/desktop/node_modules/napa/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
> node-gyp configure build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/crypt/crypt.o
../crypt.cc:18:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> init_keys (const v8::Arguments& args);
                                                              ^~~~~~~~~~~~~
                                                              v8::internal::Arguments
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../crypt.cc:20:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> ndecrypt_buf (const v8::Arguments& args);
                                                                 ^~~~~~~~~~~~~
                                                                 v8::internal::Arguments
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../crypt.cc:21:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> nencrypt_buf (const v8::Arguments& args);
                                                                 ^~~~~~~~~~~~~
                                                                 v8::internal::Arguments
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../crypt.cc:23:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
                static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                       ^~~~~~~~~~~~~
                                                       v8::internal::Arguments
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../crypt.cc:77:54: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
        Local<FunctionTemplate> tpl = FunctionTemplate::New(New);
                                                            ^~~
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../crypt.cc:78:28: error: no member named 'NewSymbol' in 'v8::String'
        tpl->SetClassName(String::NewSymbol("BinkpCrypt"));
                          ~~~~~~~~^
../crypt.cc:81:40: error: no member named 'NewSymbol' in 'v8::String'
        tpl->PrototypeTemplate()->Set(String::NewSymbol("init_keys"),
                                      ~~~~~~~~^
../crypt.cc:83:40: error: no member named 'NewSymbol' in 'v8::String'
        tpl->PrototypeTemplate()->Set(String::NewSymbol("decrypt_buf"),
                                      ~~~~~~~~^
../crypt.cc:85:40: error: no member named 'NewSymbol' in 'v8::String'
        tpl->PrototypeTemplate()->Set(String::NewSymbol("encrypt_buf"),
                                      ~~~~~~~~^
../crypt.cc:87:38: error: 'New' is a private member of 'v8::PersistentBase<v8::Function>'
        constructor = Persistent<Function>::New(tpl->GetFunction());
                                            ^
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../crypt.cc:87:16: error: too few arguments to function call, expected 2, have 1; did you mean '::BinkpCrypt::New'?
        constructor = Persistent<Function>::New(tpl->GetFunction());
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
                      ::BinkpCrypt::New
../crypt.cc:23:32: note: '::BinkpCrypt::New' declared here
                static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                             ^
../crypt.cc:88:23: error: no member named 'NewSymbol' in 'v8::String'
        exports->Set(String::NewSymbol("BinkpCrypt"), constructor);
                     ~~~~~~~~^
../crypt.cc:90:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> BinkpCrypt::New(const Arguments& args) {
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../crypt.cc:91:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../crypt.cc:92:10: error: member access into incomplete type 'const v8::internal::Arguments'
        if(!args.IsConstructCall()) {
                ^
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../crypt.cc:94:17: error: member access into incomplete type 'const v8::internal::Arguments'
                int len = args.Length();
                              ^
/Users/kud/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../crypt.cc:97:21: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        newArgs[i] = args[i];
                                     ~~~~^~
../crypt.cc:99:47: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
                Handle<Value> newInst = constructor_template->GetFunction()->NewInstance(len, newArgs);
                                        ~~~~~~~~~~~~~~~~~~~~^~
                                                            .
../crypt.cc:99:49: error: no member named 'GetFunction' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
                Handle<Value> newInst = constructor_template->GetFunction()->NewInstance(len, newArgs);
                                        ~~~~~~~~~~~~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/crypt/crypt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/kud/Projects/_playmedia/desktop/node_modules/napa/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "napa"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
```

**Comment by MWalid** [comment]
Have same issue....trying to install angular-fullstack generator...

**Comment by jljouannic** [comment]
Same here trying to install jhispter generator. It seems not specific to node 0.12. I have exactly the same behaviour with node 0.11.15 and 0.11.16.

**Comment by kud** [comment]
It's specific to node > 0.10 so?

**Comment by MWalid** [comment]
@kud not sure of that... I get this error on windows 8.1 only....had no issues on windows 7

**Comment by jljouannic** [comment]
Not specific to Windows. I get this error on Ubuntu 12.04.

**Comment by kud** [comment]
I'm on Mac OS X. I've got this error since i've updated from latest 0.10 to 0.12. 0.11 is a dev version, so maybe it's an error since 0.11 yes.

**Comment by iNfameOne** [comment]
having the same issue while trying to install imagemin-optipng

npm 2.5.0 (also tried at 2.2.\* or 2.3.*)
node v0.10.26
win7 x64

**Comment by mikeemoo** [comment]
Same here! and interesting that so many people have had this issue in the space of an hour. What's changed?

**Comment by MWalid** [comment]
So I tried to install this module directly

`npm install -g fidonet-mailer-binkp-crypt`

got the following error in red color

> C:\Program Files\nodejs\node_modules\fidonet-mailer-binkp-crypt\build\crypt.vcx
> proj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props
> " was not found. Confirm that the path in the <Import> declaration is correct,
> and that the file exists on disk.

Full log:

> C:\Program Files\nodejs\node_modules\fidonet-mailer-binkp-crypt>node "C:\Program
>  Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin
> \node-gyp.js" configure build
> Building the projects in this solution one at a time. To enable parallel build,
> please add the "/m" switch.
> C:\Program Files\nodejs\node_modules\fidonet-mailer-binkp-crypt\build\crypt.vcx
> proj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props
> " was not found. Confirm that the path in the <Import> declaration is correct,
> and that the file exists on disk.
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
> ed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
> 12)
> gyp ERR! System Windows_NT 6.2.9200
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
> les\node-gyp\bin\node-gyp.js" "configure" "build"
> gyp ERR! cwd C:\Program Files\nodejs\node_modules\fidonet-mailer-binkp-crypt
> gyp ERR! node -v v0.10.35
> gyp ERR! node-gyp -v v1.0.2
> gyp ERR! not ok
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
> \node_modules\npm\bin\npm-cli.js" "install" "-g" "fidonet-mailer-binkp-crypt
> "
> npm ERR! node v0.10.35
> npm ERR! npm  v2.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! fidonet-mailer-binkp-crypt@0.0.21 install: `node-gyp configure build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.21 install script 'node-gy
> p configure build'.
> npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt packa
> ge,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp configure build
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by jljouannic** [comment]
Back to node `0.10.36` and npm `1.4.28`. Everything works fine.

**Comment by gummiolafs** [comment]
Experiencing (what I think is) the same issues on Windows 7 SP1 with node v0.12.0 and npm 2.5.1.

cmd.exe:

```
C:\Users\Lenovo>npm install -g fidonet-mailer-binkp-crypt > output.txt
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "fidonet-mailer-binkp-crypt"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fidonet-mailer-binkp-crypt@0.0.21 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.21 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Lenovo\npm-debug.log
```

output.txt 

```

> fidonet-mailer-binkp-crypt@0.0.21 install C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
> node-gyp configure build


C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(18): error C2039: 'Arguments' : is not a member of 'v8' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(18): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(18): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(20): error C2039: 'Arguments' : is not a member of 'v8' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(20): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(20): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(21): error C2039: 'Arguments' : is not a member of 'v8' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(21): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(23): error C2039: 'Arguments' : is not a member of 'v8' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(23): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(77): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(78): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(78): error C3861: 'NewSymbol': identifier not found [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(81): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(82): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(82): error C2227: left of '->GetFunction' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(81): error C3861: 'NewSymbol': identifier not found [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(83): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(84): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(84): error C2227: left of '->GetFunction' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(83): error C3861: 'NewSymbol': identifier not found [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(85): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(86): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(86): error C2227: left of '->GetFunction' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(85): error C3861: 'NewSymbol': identifier not found [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(87): error C2660: 'v8::PersistentBase<T>::New' : function does not take 1 arguments [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(88): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(88): error C3861: 'NewSymbol': identifier not found [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(90): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(90): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(91): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(92): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(92): error C2228: left of '.IsConstructCall' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(94): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(94): error C2228: left of '.Length' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(97): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(99): error C2819: type 'v8::Persistent<T>' does not have an overloaded member 'operator ->' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(99): error C2039: 'GetFunction' : is not a member of 'v8::Persistent<T>' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(99): error C2227: left of '->NewInstance' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(105): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(105): error C2228: left of '.This' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(106): error C2039: 'Close' : is not a member of 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(106): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(106): error C2228: left of '.This' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(108): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(108): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(109): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(110): error C2039: 'AsciiValue' : is not a member of 'v8::String' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(110): error C2065: 'AsciiValue' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(110): error C2146: syntax error : missing ';' before identifier 'pass' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(110): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(110): error C2227: left of '->ToString' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(110): error C3861: 'pass': identifier not found [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(111): error C2065: 'pass' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(112): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(112): error C2228: left of '.This' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(122): error C2039: 'Close' : is not a member of 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(122): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(122): error C2228: left of '.This' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(154): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(154): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(155): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(156): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(156): error C2227: left of '->ToObject' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(157): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(157): error C2228: left of '.This' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(158): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(158): error C2227: left of '->ToObject' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(160): error C2039: 'Close' : is not a member of 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(160): error C2039: 'handle_' : is not a member of 'v8::Object' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(162): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(162): error C2143: syntax error : missing ',' before '&' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(163): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(164): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(164): error C2227: left of '->ToObject' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(165): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(165): error C2228: left of '.This' must have class/struct/union [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(166): error C2065: 'args' : undeclared identifier [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(166): error C2227: left of '->ToObject' must point to class/struct/union/generic type [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(168): error C2039: 'Close' : is not a member of 'v8::HandleScope' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
..\crypt.cc(168): error C2039: 'handle_' : is not a member of 'v8::Object' [C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt\build\binding.sln]
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'fidonet-mailer-binkp-crypt' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'fidonet-mailer-binkp-crypt', null ]
6 verbose cache add spec fidonet-mailer-binkp-crypt
7 silly cache add parsed spec { raw: 'fidonet-mailer-binkp-crypt',
7 silly cache add   scope: null,
7 silly cache add   name: 'fidonet-mailer-binkp-crypt',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed fidonet-mailer-binkp-crypt@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'fidonet-mailer-binkp-crypt',
11 silly addNameRange   range: '*',
11 silly addNameRange   hasData: false }
12 silly mapToRegistry name fidonet-mailer-binkp-crypt
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/fidonet-mailer-binkp-crypt
16 verbose addNameRange registry:https://registry.npmjs.org/fidonet-mailer-binkp-crypt not in flight; fetching
17 verbose request uri https://registry.npmjs.org/fidonet-mailer-binkp-crypt
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:30:26
20 verbose request id bb9b637651bf3c28
21 verbose etag "2SN5REJTWLVNTFQMHZUHUZVD8"
22 http request GET https://registry.npmjs.org/fidonet-mailer-binkp-crypt
23 http 304 https://registry.npmjs.org/fidonet-mailer-binkp-crypt
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 09 Feb 2015 11:30:26 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Mon, 09 Feb 2015 11:30:26 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"2SN5REJTWLVNTFQMHZUHUZVD8"',
24 silly get     age: '8',
24 silly get     'x-served-by': 'cache-lhr6321-LHR',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1423481426.787459,VS0,VE0',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/fidonet-mailer-binkp-crypt from cache
26 verbose get saving fidonet-mailer-binkp-crypt to C:\Users\Lenovo\AppData\Roaming\npm-cache\registry.npmjs.org\fidonet-mailer-binkp-crypt\.cache.json
27 silly addNameRange number 2 { name: 'fidonet-mailer-binkp-crypt', range: '*', hasData: true }
28 silly addNameRange versions [ 'fidonet-mailer-binkp-crypt',
28 silly addNameRange   [ '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.10',
28 silly addNameRange     '0.0.11',
28 silly addNameRange     '0.0.12',
28 silly addNameRange     '0.0.13',
28 silly addNameRange     '0.0.21' ] ]
29 verbose addNamed fidonet-mailer-binkp-crypt@0.0.21
30 silly addNamed semver.valid 0.0.21
31 silly addNamed semver.validRange 0.0.21
32 silly cache afterAdd fidonet-mailer-binkp-crypt@0.0.21
33 verbose afterAdd C:\Users\Lenovo\AppData\Roaming\npm-cache\fidonet-mailer-binkp-crypt\0.0.21\package\package.json not in flight; writing
34 verbose afterAdd C:\Users\Lenovo\AppData\Roaming\npm-cache\fidonet-mailer-binkp-crypt\0.0.21\package\package.json written
35 silly install resolved [ { name: 'fidonet-mailer-binkp-crypt',
35 silly install resolved     main: 'fidonet-mailer-binkp-crypt.js',
35 silly install resolved     version: '0.0.21',
35 silly install resolved     description: 'Fidonet Binkp crypt module',
35 silly install resolved     keywords: [ 'Fidonet', 'Fido', 'mailer', 'binkp' ],
35 silly install resolved     author: { name: 'Alexander N. Skovpen' },
35 silly install resolved     dependencies: {},
35 silly install resolved     devDependencies: {},
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'https://github.com/askovpen/node-fidonet-mailer-binkp-crypt.git' },
35 silly install resolved     scripts:
35 silly install resolved      { pretest: 'jshint fidonet-mailer-binkp-crypt.js',
35 silly install resolved        install: 'node-gyp configure build' },
35 silly install resolved     bugs: { url: 'https://github.com/askovpen/node-fidonet-mailer-binkp-crypt/issues' },
35 silly install resolved     _id: 'fidonet-mailer-binkp-crypt@0.0.21',
35 silly install resolved     dist:
35 silly install resolved      { shasum: '78d365b175aacd17cc7cfd55d0bbbcac499a5eab',
35 silly install resolved        tarball: 'http://registry.npmjs.org/fidonet-mailer-binkp-crypt/-/fidonet-mailer-binkp-crypt-0.0.21.tgz' },
35 silly install resolved     _from: 'fidonet-mailer-binkp-crypt@*',
35 silly install resolved     _npmVersion: '1.3.11',
35 silly install resolved     _npmUser: { name: 'askovpen', email: 'a.n.skovpen@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     directories: {},
35 silly install resolved     _shasum: '78d365b175aacd17cc7cfd55d0bbbcac499a5eab',
35 silly install resolved     _resolved: 'https://registry.npmjs.org/fidonet-mailer-binkp-crypt/-/fidonet-mailer-binkp-crypt-0.0.21.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!',
35 silly install resolved     homepage: 'https://github.com/askovpen/node-fidonet-mailer-binkp-crypt' } ]
36 info install fidonet-mailer-binkp-crypt@0.0.21 into C:\Users\Lenovo\AppData\Roaming\npm
37 info installOne fidonet-mailer-binkp-crypt@0.0.21
38 verbose installOne of fidonet-mailer-binkp-crypt to C:\Users\Lenovo\AppData\Roaming\npm not in flight; installing
39 verbose lock using C:\Users\Lenovo\AppData\Roaming\npm-cache\_locks\fidonet-mailer-binkp-cry-5e6e651fc4021dbf.lock for C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
40 silly install write writing fidonet-mailer-binkp-crypt 0.0.21 to C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
41 silly cache addNamed cb fidonet-mailer-binkp-crypt@0.0.21
42 verbose unbuild node_modules\fidonet-mailer-binkp-crypt
43 verbose gentlyRm vacuuming C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
44 verbose tar unpack C:\Users\Lenovo\AppData\Roaming\npm-cache\fidonet-mailer-binkp-crypt\0.0.21\package.tgz
45 verbose tar unpacking to C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
46 verbose gentlyRm vacuuming C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
47 silly gunzTarPerm modes [ '777', '666' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
50 silly gunzTarPerm extractEntry README.md
51 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
52 silly gunzTarPerm extractEntry LICENSE
53 silly gunzTarPerm modified mode [ 'LICENSE', 420, 438 ]
54 silly gunzTarPerm extractEntry fidonet-mailer-binkp-crypt.js
55 silly gunzTarPerm modified mode [ 'fidonet-mailer-binkp-crypt.js', 420, 438 ]
56 silly gunzTarPerm extractEntry binding.gyp
57 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
58 silly gunzTarPerm extractEntry crypt.cc
59 silly gunzTarPerm modified mode [ 'crypt.cc', 420, 438 ]
60 info preinstall fidonet-mailer-binkp-crypt@0.0.21
61 silly install resolved []
62 verbose about to build C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
63 info build C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
64 verbose linkStuff [ true,
64 verbose linkStuff   'C:\\Users\\Lenovo\\AppData\\Roaming\\npm\\node_modules',
64 verbose linkStuff   true,
64 verbose linkStuff   'C:\\Users\\Lenovo\\AppData\\Roaming\\npm\\node_modules' ]
65 info linkStuff fidonet-mailer-binkp-crypt@0.0.21
66 verbose linkBins fidonet-mailer-binkp-crypt@0.0.21
67 verbose linkMans fidonet-mailer-binkp-crypt@0.0.21
68 verbose rebuildBundles fidonet-mailer-binkp-crypt@0.0.21
69 info install fidonet-mailer-binkp-crypt@0.0.21
70 verbose unsafe-perm in lifecycle true
71 info fidonet-mailer-binkp-crypt@0.0.21 Failed to exec install script
72 verbose unlock done using C:\Users\Lenovo\AppData\Roaming\npm-cache\_locks\fidonet-mailer-binkp-cry-5e6e651fc4021dbf.lock for C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
73 verbose stack Error: fidonet-mailer-binkp-crypt@0.0.21 install: `node-gyp configure build`
73 verbose stack Exit status 1
73 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
73 verbose stack     at EventEmitter.emit (events.js:110:17)
73 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
73 verbose stack     at ChildProcess.emit (events.js:110:17)
73 verbose stack     at maybeClose (child_process.js:1008:16)
73 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
74 verbose pkgid fidonet-mailer-binkp-crypt@0.0.21
75 verbose cwd C:\Users\Lenovo
76 error Windows_NT 6.1.7601
77 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "fidonet-mailer-binkp-crypt"
78 error node v0.12.0
79 error npm  v2.5.1
80 error code ELIFECYCLE
81 error fidonet-mailer-binkp-crypt@0.0.21 install: `node-gyp configure build`
81 error Exit status 1
82 error Failed at the fidonet-mailer-binkp-crypt@0.0.21 install script 'node-gyp configure build'.
82 error This is most likely a problem with the fidonet-mailer-binkp-crypt package,
82 error not with npm itself.
82 error Tell the author that this fails on your system:
82 error     node-gyp configure build
82 error You can get their info via:
82 error     npm owner ls fidonet-mailer-binkp-crypt
82 error There is likely additional logging output above.
83 verbose exit [ 1, true ]
84 verbose unbuild node_modules\fidonet-mailer-binkp-crypt
85 info preuninstall fidonet-mailer-binkp-crypt@0.0.21
86 info uninstall fidonet-mailer-binkp-crypt@0.0.21
87 verbose unbuild rmStuff fidonet-mailer-binkp-crypt@0.0.21 from C:\Users\Lenovo\AppData\Roaming\npm\node_modules
88 info postuninstall fidonet-mailer-binkp-crypt@0.0.21
89 verbose gentlyRm vacuuming C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
90 silly gentlyRm purging C:\Users\Lenovo\AppData\Roaming\npm\node_modules\fidonet-mailer-binkp-crypt
91 silly gentlyRm quitting because other entries in C:\Users\Lenovo\AppData\Roaming\npm\node_modules

```

**Comment by pastur** [comment]
Same issue here:
Windows 7 64bit
node 0.10.33
npm 2.1.11

**Comment by kud** [comment]
Gosh, I removed a module which uses this one, but another module is also this one. This module is everywhere.

**Comment by rachitGulati** [comment]
Same issue here :-
with window 7 32bit
node 0.10.30
npm 1.4.21 

while installing 
npm install -g generator-meanjs 

or

npm install -g generator-angular-fullstack

**Comment by dcopestake** [comment]
I'm having issues with this as well. I guess this is all being triggered because [adm-zip](https://www.npmjs.com/package/adm-zip) updated earlier today?!?

There don't appear to have been any commits for a long time though, so not sure why it's failing all of a sudden?

**Comment by kud** [comment]
`/Users/kud/Projects/_playmedia/desktop/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt`

Could be the current project or adm-zip or decompress-unzip or download or etc etc etc. And i'm on node 0.12. I'm rolling back to node 0.10 right now.

**Comment by saslamcol** [comment]
so do we just wait? (new to this)

**Comment by kud** [comment]
Is it a problem with `.node-gyp/0.12.0/deps/v8`?

**Comment by Aaike** [comment]
lol , ok i was thinking i was the only one in the world with this problem until i found this issue

**Comment by kud** [comment]
A workaround: come back to node.js 0.10.36.

On Mac OS X with brew: 

``` console
$ brew remove node
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew/06b10bc64605ece33b56d2607a1480cf8177fd8f/Library/Formula/node.rb
```

**Comment by MWalid** [comment]
@kud still no luck on windows....my node.js v is 0.10.35 !!

**Comment by saslamcol** [comment]
i just got this on the end :1:
Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
anyone else?

**Comment by askovpen** [comment]
this module was written for node 0.10. If you have patches for 0.12 - welcome :-)

**Comment by MWalid** [comment]
@askovpen my node v is 0.10.35, any suggested workarounds?

**Comment by saslamcol** [comment]
how can i install npm install -g generator-meanjs without the errors?

**Comment by Globegitter** [comment]
Does not work for [iojs](https://iojs.org/) 1.1 either.

**Comment by MWalid** [comment]
Tried following versions:

node 0.10.35
node 0.10.36
node 0.12.0

none of them worked :(

os: windows 8.1

**Comment by newaeonweb** [comment]
Same issue here, windows 7, Node 0.10.28, npm 1.4.9. Trying to install generator-angm.

**Comment by karlprieb** [comment]
Tried with: 

node 0.10.35 and 0.10.36
npm 2.5.0 and 1.4.28

No success.

**Comment by banjankri** [comment]
whoah, spent like 2 hours trying to figure out what happened - if somebody has a workaround for windows 7, would love to hear it

**Comment by dcopestake** [comment]
What I'm confused about, is that I'm seeing issues with this as a result of a dependency chain which starts at [grunt-contrib-imagemin](https://www.npmjs.com/package/grunt-contrib-imagemin) and eventually ends up at [adm-zip](https://www.npmjs.com/package/adm-zip) and then this, but, as far as I can see _this_ package hasn't updated since 2014, and it doesn't look like any of the parent packages have only just started using it, so I've no idea how this ever worked before?!?

**Comment by terencenero** [comment]
Hi has any found any solution I am getting the same error while installing Yeoman

**Comment by JohanBeekers** [comment]
Trying to install Yeoman and some generators. Both Yeoman and generators give this problem in 10.36. In 12.0 Yeoman installs fine but the generators still won't install.

**Comment by pastur** [comment]
This is the error I'm seeing in my machine: 
`
\node_modules\grunt-contrib-imagemin\node_modules\pngquant-bin\node_modules\bin
-wrapper\node_modules\download\node_modules\decompress\node_modules\adm-zip\node_modules\fidonet-mailer-binkp-crypt {git
}
{lamb} node "C:\Users\apastur\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\nod
e-gyp.js" configure build
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
`

**Comment by dcopestake** [comment]
@pastur node-gyp needs [Python 2.7](https://www.python.org/downloads/release/python-279/) to work.

**Comment by benny20832** [comment]
I have also a problem with this:

``` xml
34247 verbose unlock done using C:\Users\bgu\AppData\Roaming\npm-cache\_locks\grunt-contrib-imagemin-9910591f0f90d1df.lock for C:\Dev\projects\cgmeserviceswebedition\node_modules\grunt-contrib-imagemin
34248 verbose stack Error: fidonet-mailer-binkp-crypt@0.0.21 install: `node-gyp configure build`
34248 verbose stack Exit status 1
34248 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
34248 verbose stack     at EventEmitter.emit (events.js:110:17)
34248 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
34248 verbose stack     at ChildProcess.emit (events.js:110:17)
34248 verbose stack     at maybeClose (child_process.js:1008:16)
34248 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
34249 verbose pkgid fidonet-mailer-binkp-crypt@0.0.21
34250 verbose cwd C:\Dev\projects\cgmeserviceswebedition
34251 error Windows_NT 6.1.7601
34252 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
34253 error node v0.12.0
34254 error npm  v2.5.1
34255 error code ELIFECYCLE
34256 error fidonet-mailer-binkp-crypt@0.0.21 install: `node-gyp configure build`
34256 error Exit status 1
34257 error Failed at the fidonet-mailer-binkp-crypt@0.0.21 install script 'node-gyp configure build'.
34257 error This is most likely a problem with the fidonet-mailer-binkp-crypt package,
34257 error not with npm itself.
34257 error Tell the author that this fails on your system:
34257 error     node-gyp configure build
34257 error You can get their info via:
34257 error     npm owner ls fidonet-mailer-binkp-crypt
34257 error There is likely additional logging output above.
34258 verbose exit [ 1, true ]
```

**Comment by deniaz** [comment]
I had the same issue with node v0.12.0 but after downgrading to v0.10.36 everything worked fine.

**Comment by raza2022** [comment]
OMG I think am the only person getting this error, and working hard with system configuration since last 2 hours..........

**Comment by kud** [comment]
Same @deniaz

**Comment by chetankumar01** [comment]
I'm using node v0.10.6 with npm  2.5.0, still getting the error

**Comment by terencenero** [comment]
Hi I have tried on 3 Machines but still face same error

**Comment by pastur** [comment]
@dcopestake yes, I think I can still understand error messages. The funny thing is my build was working perfectly with python 3 until now. So maybe node-gyp was not being used?

**Comment by Romanx** [comment]
@pastur Same here. I'm using gulp-imagemin which has an underlying dependencies which use this library. Python 3 has worked fine until today.

**Comment by dcopestake** [comment]
@pastur Just trying to help.

**Comment by pastur** [comment]
@dcopestake I know, and I appreciate that

**Comment by dcopestake** [comment]
This package hasn't changed since June 2014, so I'd be surprised if it was anything specific to this. It feels more likely that everyone is running into issues - and different ones at that - because some other package has added a dependency that ends up here.

**Comment by rmg** [comment]
adm-zip has only depended on this module for about 6 hours.. that's why the break only appeared today. See cthackers/adm-zip#121.

**Comment by dcopestake** [comment]
Damn, didn't spot that because the [commit which introduced the dependency](https://github.com/cthackers/adm-zip/commit/ecc414f741256d3b3f80ced9c0eb8ff48fec7433) was in 2014 but the package was only just actually updated today! Well spotted @rmg.

**Comment by ralucaStan** [comment]
I've been dealing all day with this. Last night it worked so I knew it must have been something that happend today. so now we wait

**Comment by ocombe** [comment]
You guys should try to set the version of adm-zip in your package.json. I did that and now I can install imagemin without any problem:
`npm install --save-dev adm-zip@0.4.4`

**Comment by askovpen** [comment]
fixed 58ff1909d827847f55499eaee62793a8bcb40fd6

**Comment by MWalid** [comment]
@askovpen how can I apply the fix?

**Comment by ajmalbabu** [comment]
after the commit "npm install -g generator-angular" still fails do i need to install anything differently

**Comment by MWalid** [comment]
I could install this package directly like the following:

`npm install -g fidonet-mailer-binkp-crypt --msvs_version=2013`

but it still fails when trying to install `angular-fullstack` generator...

**Comment by MWalid** [comment]
Now I get the following errors:

> C:\Users\Walid\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node
> _modules\yeoman-generator\node_modules\download\node_modules\decompress\node_mod
> ules\decompress-unzip\node_modules\adm-zip\node_modules\fidonet-mailer-binkp-cry
> pt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_m
> odules\node-gyp\bin\node-gyp.js" configure build
> child_process: customFds option is deprecated, use stdio instead.
> gyp: C:\Users\Walid\AppData\Roaming\npm\node_modules\generator-angular-fullstack
> \node_modules\yeoman-generator\node_modules\download\node_modules\decompress\nod
> e_modules\decompress-unzip\node_modules\adm-zip\node_modules\fidonet-mailer-bink
> p-crypt\build\config.gypi not found (cwd: C:\Users\Walid\AppData\Roaming\npm\nod
> e_modules\generator-angular-fullstack\node_modules\yeoman-generator\node_modules
> \download\node_modules\decompress\node_modules\decompress-unzip\node_modules\adm
> -zip\node_modules\fidonet-mailer-binkp-crypt) while reading includes of binding.
> gyp while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
> s\npm\node_modules\node-gyp\lib\configure.js:343:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
> :12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
> les\node-gyp\bin\node-gyp.js" "configure" "build"
> gyp ERR! cwd C:\Users\Walid\AppData\Roaming\npm\node_modules\generator-angular-f
> ullstack\node_modules\yeoman-generator\node_modules\download\node_modules\decomp
> ress\node_modules\decompress-unzip\node_modules\adm-zip\node_modules\fidonet-mai
> ler-binkp-crypt
> gyp ERR! node -v v0.12.0
> gyp ERR! node-gyp -v v1.0.2
> gyp ERR! not ok
> /
> yo@1.4.5 postinstall C:\Users\Walid\AppData\Roaming\npm\node_modules\generator
> -angular-fullstack\node_modules\yo
> yodoctor
> Yeoman Doctor
> Running sanity checks on your system
> √ Global configuration file is valid
> √ NODE_PATH matches the npm root
> √ No .bowerrc file in home directory
> √ No .yo-rc.json file in home directory
> Everything looks all right!
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
> \node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-angular-fullstac
> k" "--msvs_version=2013"
> npm ERR! node v0.12.0
> npm ERR! npm  v2.5.1
> npm ERR! code ELIFECYCLE
> npm ERR! fidonet-mailer-binkp-crypt@0.0.23 install: `node-gyp configure build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.23 install script 'node-gy
> p configure build'.
> npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt packa
> ge,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp configure build
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Walid\npm-debug.log
